import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Share,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../src/theme/colors';
import api from '../src/services/api';

interface GroceryList {
  meal_plan_id: string;
  days_covered: number;
  total_items: number;
  grocery_list: { [category: string]: string[] };
}

const categoryIcons: { [key: string]: string } = {
  'Proteins': 'fish',
  'Produce': 'leaf',
  'Dairy & Eggs': 'water',
  'Grains & Bread': 'nutrition',
  'Pantry Items': 'cube',
  'Frozen': 'snow',
  'Other': 'ellipsis-horizontal',
};

export default function GroceryListScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  const mealPlanId = params.mealPlanId as string;
  const [loading, setLoading] = useState(true);
  const [groceryData, setGroceryData] = useState<GroceryList | null>(null);
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set());
  const [selectedDays, setSelectedDays] = useState(7);

  useEffect(() => {
    if (mealPlanId) {
      loadGroceryList();
    }
  }, [mealPlanId, selectedDays]);

  const loadGroceryList = async () => {
    setLoading(true);
    try {
      const response = await api.get(`/mealplan/${mealPlanId}/grocery-list?days=${selectedDays}`);
      setGroceryData(response.data);
    } catch (error) {
      console.error('Failed to load grocery list:', error);
    } finally {
      setLoading(false);
    }
  };

  const toggleItem = (item: string) => {
    const newChecked = new Set(checkedItems);
    if (newChecked.has(item)) {
      newChecked.delete(item);
    } else {
      newChecked.add(item);
    }
    setCheckedItems(newChecked);
  };

  const shareList = async () => {
    if (!groceryData) return;
    
    let listText = `🛒 Grocery List (${groceryData.days_covered} days)\n\n`;
    
    Object.entries(groceryData.grocery_list).forEach(([category, items]) => {
      listText += `📦 ${category}\n`;
      items.forEach(item => {
        const checked = checkedItems.has(item);
        listText += `${checked ? '✅' : '○'} ${item}\n`;
      });
      listText += '\n';
    });
    
    listText += `\nGenerated by InterFitAI`;
    
    try {
      await Share.share({
        message: listText,
        title: 'My Grocery List',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const getTotalChecked = () => {
    if (!groceryData) return 0;
    let total = 0;
    Object.values(groceryData.grocery_list).forEach(items => {
      items.forEach(item => {
        if (checkedItems.has(item)) total++;
      });
    });
    return total;
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.loadingText}>Generating grocery list...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (!groceryData) {
    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.header}>
          <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
            <Ionicons name="arrow-back" size={24} color={colors.text} />
          </TouchableOpacity>
          <Text style={styles.title}>Grocery List</Text>
          <View style={{ width: 40 }} />
        </View>
        <View style={styles.emptyContainer}>
          <Ionicons name="cart-outline" size={64} color={colors.textMuted} />
          <Text style={styles.emptyText}>Unable to generate grocery list</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={24} color={colors.text} />
        </TouchableOpacity>
        <Text style={styles.title}>Grocery List</Text>
        <TouchableOpacity onPress={shareList} style={styles.shareBtn}>
          <Ionicons name="share-outline" size={24} color={colors.primary} />
        </TouchableOpacity>
      </View>

      {/* Day Selector */}
      <View style={styles.daySelector}>
        {[3, 5, 7].map(days => (
          <TouchableOpacity
            key={days}
            style={[styles.dayOption, selectedDays === days && styles.dayOptionActive]}
            onPress={() => setSelectedDays(days)}
          >
            <Text style={[styles.dayOptionText, selectedDays === days && styles.dayOptionTextActive]}>
              {days} Days
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Progress Bar */}
      <View style={styles.progressContainer}>
        <View style={styles.progressInfo}>
          <Text style={styles.progressText}>
            {getTotalChecked()} of {groceryData.total_items} items
          </Text>
          <Text style={styles.progressPercent}>
            {Math.round((getTotalChecked() / groceryData.total_items) * 100)}%
          </Text>
        </View>
        <View style={styles.progressBar}>
          <View 
            style={[
              styles.progressFill, 
              { width: `${(getTotalChecked() / groceryData.total_items) * 100}%` }
            ]} 
          />
        </View>
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {Object.entries(groceryData.grocery_list).map(([category, items]) => (
          <View key={category} style={styles.categorySection}>
            <View style={styles.categoryHeader}>
              <View style={styles.categoryIconWrap}>
                <Ionicons 
                  name={(categoryIcons[category] || 'ellipsis-horizontal') as any} 
                  size={20} 
                  color={colors.primary} 
                />
              </View>
              <Text style={styles.categoryTitle}>{category}</Text>
              <Text style={styles.categoryCount}>{items.length}</Text>
            </View>
            
            {items.map((item, index) => (
              <TouchableOpacity
                key={`${category}-${index}`}
                style={styles.itemRow}
                onPress={() => toggleItem(item)}
              >
                <View style={[styles.checkbox, checkedItems.has(item) && styles.checkboxChecked]}>
                  {checkedItems.has(item) && (
                    <Ionicons name="checkmark" size={16} color="#fff" />
                  )}
                </View>
                <Text style={[styles.itemText, checkedItems.has(item) && styles.itemTextChecked]}>
                  {item}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        ))}
        
        <View style={styles.footer}>
          <Text style={styles.footerText}>
            Tap items to check them off as you shop
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.textSecondary,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
  },
  shareBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
  },
  daySelector: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 16,
  },
  dayOption: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: colors.surface,
    alignItems: 'center',
  },
  dayOptionActive: {
    backgroundColor: colors.primary,
  },
  dayOptionText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  dayOptionTextActive: {
    color: '#000',
  },
  progressContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  progressInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  progressText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  progressPercent: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  progressBar: {
    height: 8,
    backgroundColor: colors.surface,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  categorySection: {
    marginBottom: 24,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary + '20',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  categoryTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  categoryCount: {
    fontSize: 14,
    color: colors.textMuted,
    backgroundColor: colors.surface,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: colors.surface,
    borderRadius: 10,
    marginBottom: 6,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.border,
    marginRight: 14,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  itemText: {
    flex: 1,
    fontSize: 15,
    color: colors.text,
  },
  itemTextChecked: {
    textDecorationLine: 'line-through',
    color: colors.textMuted,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    color: colors.textMuted,
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  footerText: {
    fontSize: 13,
    color: colors.textMuted,
  },
});
